[project]
name = "agent.py"
version = "0.1.0"
description = "Run an AI agent"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typer>=0.19.2"
]

[project.scripts]
agent = "agent:cli"
